// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션/스키마 엔진 전용 — Supabase pooler(6543)가 아닌 direct(5432) 연결 사용.
    url: process.env["DIRECT_URL"],
  },
});
